### ISSUE TITLE
Arabic Embedded Subtitles (Text not PGS)

### ISSUE THREAD

**Issue by ozone1864** [e2iplayer/exteplayer3#18]
Dear SamSamSam,
Movies with embedded Arabic text subtitles are not caught by **exteplayer3** but all other languages work fine can you check.

{"s_l": [{"id":3,"e":"S_TEXT/SUBRIP","n":"ita"}, {"id":4,"e":"S_TEXT/SUBRIP","n":"eng"}, {"id":5,"e":"S_TEXT/SUBRIP","n":"eng"}, {"id":6,"e":"S_TEXT/SUBRIP","n":"spa"}, {"id":7,"e":"S_TEXT/SUBRIP","n":"spa"}, {"id":8,"e":"S_TEXT/SUBRIP","n":"fre"}, {"id":9,"e":"S_TEXT/SUBRIP","n":"ger"}, {"id":10,"e":"S_TEXT/SUBRIP","n":"ita"}, {"id":11,"e":"S_TEXT/SUBRIP","n":"por"}, {"id":12,"e":"S_TEXT/SUBRIP","n":"por"}, {"id":13,"e":"S_TEXT/SUBRIP","n":"pol"}, {"id":14,"e":"S_TEXT/SUBRIP","n":"tur"}, {"id":15,"e":"S_TEXT/SUBRIP","n":"swe"}, {"id":16,"e":"S_TEXT/SUBRIP","n":"dan"}, {"id":17,"e":"S_TEXT/SUBRIP","n":"fin"}, {"id":18,"e":"S_TEXT/SUBRIP","n":"dut"}, {"id":19,"e":"S_TEXT/SUBRIP","n":"nor"}, {"id":20,"e":"S_TEXT/SUBRIP","n":"rus"}, {"id":21,"e":"S_TEXT/SUBRIP","n":"gre"}, {"id":22,"e":"S_TEXT/SUBRIP","n":"heb"}]}
{"s_c":{"id":-1,"e":"","n":""}}

But as you can see here 

![Subtitles](https://user-images.githubusercontent.com/45090310/57584301-4b85c680-74e2-11e9-8ea2-8958bda39ed5.png)

Best Regards,

**Comment by e2iplayer** [comment]
Hello,

Please provide sample file.

**Comment by ozone1864** [comment]
Hello,
This is a torrent attached you can download at least 5% and check the episode
[sample.zip](https://github.com/e2iplayer/exteplayer3/files/3170327/sample.zip)

**Comment by e2iplayer** [comment]
I do not plan to download something from torrent.
Please attach sample here.

**Comment by e2iplayer** [comment]
Your problem is most probably related to the fact that there is limit to 20 subtitle tracks.
However it will be better to confirm this before. So, please provide sample.
You can simple cut part of your file from the beginning and attach here.

For example you can use 

> dd

for this purpose.

**Comment by ozone1864** [comment]
Hello,
Please find the attached sample.
[The.Protector.2018.2x01.1080p.NF.WEB-DLMux.DD5.1.x264-SAMPLE.zip](https://github.com/e2iplayer/exteplayer3/files/3171295/The.Protector.2018.2x01.1080p.NF.WEB-DLMux.DD5.1.x264-SAMPLE.zip)

**Comment by e2iplayer** [comment]
Should be fixed. https://github.com/e2iplayer/exteplayer3/commit/b66e1666c8440a42eca54185179a2adc33bfd587

**Comment by ozone1864** [comment]
Thank you, will test tonight !

**Comment by ozone1864** [comment]
Still didn't work after installing latest exteplayer3

{"s_l": [{"id":3,"e":"S_TEXT/SUBRIP","n":"ita"}, {"id":4,"e":"S_TEXT/SUBRIP","n":"eng"}, {"id":5,"e":"S_TEXT/SUBRIP","n":"eng"}, {"id":6,"e":"S_TEXT/SUBRIP","n":"spa"}, {"id":7,"e":"S_TEXT/SUBRIP","n":"spa"}, {"id":8,"e":"S_TEXT/SUBRIP","n":"fre"}, {"id":9,"e":"S_TEXT/SUBRIP","n":"ger"}, {"id":10,"e":"S_TEXT/SUBRIP","n":"ita"}, {"id":11,"e":"S_TEXT/SUBRIP","n":"por"}, {"id":12,"e":"S_TEXT/SUBRIP","n":"por"}, {"id":13,"e":"S_TEXT/SUBRIP","n":"pol"}, {"id":14,"e":"S_TEXT/SUBRIP","n":"tur"}, {"id":15,"e":"S_TEXT/SUBRIP","n":"swe"}, {"id":16,"e":"S_TEXT/SUBRIP","n":"dan"}, {"id":17,"e":"S_TEXT/SUBRIP","n":"fin"}, {"id":18,"e":"S_TEXT/SUBRIP","n":"dut"}, {"id":19,"e":"S_TEXT/SUBRIP","n":"nor"}, {"id":20,"e":"S_TEXT/SUBRIP","n":"rus"}, {"id":21,"e":"S_TEXT/SUBRIP","n":"gre"}, {"id":22,"e":"S_TEXT/SUBRIP","n":"heb"}]}
{"s_c":{"id":-1,"e":"","n":""}}

**Comment by e2iplayer** [comment]
What do you mean by "last version"?

Użytkownik ozone1864 <notifications@github.com> napisał:

**Comment by ozone1864** [comment]
Installed the latest exteplayer3 version from the source but still didn't catch more than 20 subs
The commit you did today still not live yet ?

**Comment by e2iplayer** [comment]
> Installed the latest exteplayer3 version from the source 

what does this mean?

At the beginning exteplayer3 print it's version. So, at first I will suggest you to check your exteplayer3 version or compile it from the source.

The last version is v68 and you should know this by checking commit changes.

**Comment by ozone1864** [comment]
This is installing version 67
wget http://www.e2iplayer.gitlab.io/resources/packages/bin/armv7/exteplayer3_fpu_hard_ffmpeg4.1 -O /iptvplayer_rootfs/usr/bin/exteplayer3 && chmod 777 /iptvplayer_rootfs/usr/bin/exteplayer3
